export const SingleInstrumentsData = [
  {
    id: 1,
    instrument_name: "Adson points",
    instrument_id: "G0",
    instrument_quantity: "1",
    instrument_location: "Carousel",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/400%2010-162.png",
  },
  {
    id: 2,
    instrument_name: "Allis",
    instrument_id: "G1",
    instrument_quantity: "1",
    instrument_location: "Carousel",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/AllisForceps56.jpg",
  },
  {
    id: 3,
    instrument_name: "Awl",
    instrument_id: "G2",
    instrument_quantity: "1",
    instrument_location: "OR",
    instrument_image:
      "https://www.integralife.com/ccstore/v1/images/?source=/file/v634622050409593382/products/M823B-GRAY.jpg",
  },
  {
    id: 4,
    instrument_name: "Alternate energy device",
    instrument_id: "G3",
    instrument_quantity: "1",
    instrument_location: "OR",
    instrument_image:
      "https://www.olympus-global.com/technology/design/story/surgicalenergydevice/images/img_02.jpg",
  },
  {
    id: 5,
    instrument_name: "Babcock",
    instrument_id: "G4",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
    instrument_image:
      "https://animalab.eu/images/e1934af3-6823-414a-94e0-895f35b7a6a2/504218.jpg",
  },
  {
    id: 6,
    instrument_name: "Biopsy forceps",
    instrument_id: "G5",
    instrument_quantity: "1",
    instrument_location: "OR",
    instrument_image:
      "https://dtrmedical.com/wp-content/uploads/2014/11/OralBiopsyForceps90mm.jpg",
  },
  {
    id: 7,
    instrument_name: "Bone cutter",
    instrument_id: "G6",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
    instrument_image:
      "https://lifeinstruments.com/wp-content/uploads/2020/11/Rongeurs-Stille_Horsely_Bone_Cutter.jpg",
  },
  {
    id: 8,
    instrument_name: "Bone holder",
    instrument_id: "G7",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
    instrument_image:
      "https://www.innomed.net/Images/prod_shots_430/FaillaceExtraSmallBoneClamp_1171.jpg",
  },
  {
    id: 9,
    instrument_name: "Bone rongeur",
    instrument_id: "G8",
    instrument_quantity: "1",
    instrument_location: "Carousel",
    instrument_image:
      "https://www.stille.se/wp-content/uploads/2019/12/1200x1200_105-17230.jpg",
  },
  {
    id: 10,
    instrument_name: "Bowel clamp",
    instrument_id: "G9",
    instrument_quantity: "1",
    instrument_location: "OR",
    instrument_image:
      "https://surgical-instruments.bbraun.com/medias/ea126h1-50.jpg?context=bWFzdGVyfHJvb3R8MTUzOTQwfGltYWdlL2pwZWd8aDk1L2g5MC8xMjExNTg5NDk2MDE1OC5qcGd8NGY4M2FkMzkxNzJkMDQ1YmIxMTI1YjI1MzM3OTRhOTdkNTE3YWViMDhjYTQzMzI2Njg0ZjQ2YzI1MTEwNGE3OQ",
  },
  {
    id: 11,
    instrument_name: "Caliper",
    instrument_id: "G10",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 12,
    instrument_name: "Catheter",
    instrument_id: "G11",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 13,
    instrument_name: "Clip inserter",
    instrument_id: "G12",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 14,
    instrument_name: "Coagulation forcep",
    instrument_id: "G13",
    instrument_quantity: "1",
    instrument_location: "Carousel",
  },
  {
    id: 15,
    instrument_name: "Corkscrew",
    instrument_id: "G14",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 16,
    instrument_name: "Currette",
    instrument_id: "G15",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 17,
    instrument_name: "Dilator",
    instrument_id: "G16",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 18,
    instrument_name: "Dissector metal",
    instrument_id: "G17",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 19,
    instrument_name: "Duval",
    instrument_id: "G18",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 20,
    instrument_name: "Finochietto forceps",
    instrument_id: "G19",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 21,
    instrument_name: "Fraser",
    instrument_id: "G20",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 22,
    instrument_name: "G-william",
    instrument_id: "G21",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 23,
    instrument_name: "Hartman",
    instrument_id: "G22",
    instrument_quantity: "1",
    instrument_location: "Carousel",
  },
  {
    id: 24,
    instrument_name: "Heaney",
    instrument_id: "G23",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 25,
    instrument_name: "Hemostat",
    instrument_id: "G24",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/405-3-325.jpg",
  },
  {
    id: 26,
    instrument_name: "Hook",
    instrument_id: "G25",
    instrument_quantity: "1",
    instrument_location: "OR",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/400-MH21-89.jpg",
  },
  {
    id: 27,
    instrument_name: "Kelly",
    instrument_id: "G26",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/405-2561C.jpg",
  },
  {
    id: 28,
    instrument_name: "Kocher",
    instrument_id: "G27",
    instrument_quantity: "1",
    instrument_location: "OR",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/Rochester-Ochner%20Forceps_I.jpg",
  },
  {
    id: 29,
    instrument_name: "Lower",
    instrument_id: "G28",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 30,
    instrument_name: "Marking pen",
    instrument_id: "G29",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 31,
    instrument_name: "Mixter",
    instrument_id: "G30",
    instrument_quantity: "1",
    instrument_location: "Carousel",
  },
  {
    id: 32,
    instrument_name: "Mosquito",
    instrument_id: "G31",
    instrument_quantity: "1",
    instrument_location: "OR",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/400-12-131.png",
  },
  {
    id: 33,
    instrument_name: "Needle holder",
    instrument_id: "G32",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/400%2024-150.jpg",
  },
  {
    id: 34,
    instrument_name: "Overholts",
    instrument_id: "G33",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 35,
    instrument_name: "Periosteal elevator",
    instrument_id: "G34",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 36,
    instrument_name: "Plucker/Rommel",
    instrument_id: "G35",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 37,
    instrument_name: "Probe/groove",
    instrument_id: "G36",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 38,
    instrument_name: "Retractor",
    instrument_id: "G37",
    instrument_quantity: "1",
    instrument_location: "Carousel",
  },
  {
    id: 39,
    instrument_name: "Rib approx",
    instrument_id: "G38",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 40,
    instrument_name: "Rib stripper",
    instrument_id: "G39",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 41,
    instrument_name: "Rogers",
    instrument_id: "G40",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 42,
    instrument_name: "Rodney Maingot",
    instrument_id: "G41",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 43,
    instrument_name: "Ruler",
    instrument_id: "G42",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 44,
    instrument_name: "Scanlop",
    instrument_id: "G43",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 45,
    instrument_name: "Scalpel handle",
    instrument_id: "G44",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 46,
    instrument_name: "Scissors",
    instrument_id: "G45",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 47,
    instrument_name: "Semb",
    instrument_id: "G45",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 48,
    instrument_name: "Sizer",
    instrument_id: "G47",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 49,
    instrument_name: "Sound",
    instrument_id: "G48",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 50,
    instrument_name: "Speculum",
    instrument_id: "G49",
    instrument_quantity: "1",
    instrument_location: "Carousel",
  },
  {
    id: 51,
    instrument_name: "Sponge stick",
    instrument_id: "G50",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 52,
    instrument_name: "Stone forceps",
    instrument_id: "G51",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 53,
    instrument_name: "Suctions",
    instrument_id: "G52",
    instrument_quantity: "1",
    instrument_location: "OR",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/900-299.jpg",
  },
  {
    id: 54,
    instrument_name: "Swedish debakey",
    instrument_id: "G53",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 55,
    instrument_name: "Sympathectomy forceps",
    instrument_id: "G54",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 56,
    instrument_name: "Tenaculum",
    instrument_id: "G55",
    instrument_quantity: "1",
    instrument_location: "Carousel",
    instrument_image:
      "https://us.evocdn.io/dealer/1152/catalog/product/images/400%2064-410%20copy.jpg",
  },
  {
    id: 57,
    instrument_name: "Tissues",
    instrument_id: "G56",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 58,
    instrument_name: "Tonsil",
    instrument_id: "G57",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 59,
    instrument_name: "Towel clip",
    instrument_id: "G58",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 60,
    instrument_name: "Uterine injector",
    instrument_id: "G59",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
  {
    id: 61,
    instrument_name: "Uterine forceps",
    instrument_id: "G60",
    instrument_quantity: "1",
    instrument_location: "OR",
  },
  {
    id: 62,
    instrument_name: "Vascular clamps",
    instrument_id: "G61",
    instrument_quantity: "1",
    instrument_location: "Sterilization",
  },
];
