export const SingleInstrumentsData = [
  {
    "id":1,
    "instrument_name": "Adson points",
    "instrument_id": "G1000",
    "instrument_quantity": "1",
    "instrument_location": "Carousel",
  },
  {
    "id":2,
    "instrument_name": "Allis",
    "instrument_id": "G1001",
    "instrument_quantity": "1",
    "instrument_location": "Carousel",
  },
  {
    "id":3,
    "instrument_name": "Awl",
    "instrument_id": "G1002",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":4,
    "instrument_name": "Alternate energy device",
    "instrument_id": "G1003",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":5,
    "instrument_name": "Babcock",
    "instrument_id": "G1004",
    "instrument_quantity": "1",
    "instrument_location": "Sterilization",
  },
  {
    "id":6,
    "instrument_name": "Biopsy forceps",
    "instrument_id": "G1005",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":7,
    "instrument_name": "Bone cutter",
    "instrument_id": "G1006",
    "instrument_quantity": "1",
    "instrument_location": "Sterilization",
  },
  {
    "id":8,
    "instrument_name": "Bone holder",
    "instrument_id": "G1007",
    "instrument_quantity": "1",
    "instrument_location": "Sterilization",
  },
  {
    "id":9,
    "instrument_name": "Bone rongeur",
    "instrument_id": "G1008",
    "instrument_quantity": "1",
    "instrument_location": "Carousel",
  },
  {
    "id":10,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1009",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":11,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1009",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":12,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1010",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":13,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1011",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":14,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1012",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":15,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1013",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":16,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1014",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":17,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1015",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":18,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1016",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":19,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1017",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":20,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1018",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
  {
    "id":21,
    "instrument_name": "Bowel clamp",
    "instrument_id": "G1019",
    "instrument_quantity": "1",
    "instrument_location": "OR",
  },
]